# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

arr = np.random.uniform(0, 20, size=(4,7)) # Сгенерировать двухмерный массив arr размерности (4, 7) в диапазоне от 0 до 20
print(arr)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[[10.00542555 16.29498986  1.95026628  4.49038113  9.4310979   0.72437358
  18.28135447]
 [18.01165888  3.38001319  7.78998366  4.88811053 10.80183975 12.97195957
  11.26212287]
 [17.073103   18.21139849  0.10505062  8.14522568  2.94816735  8.26348022
  16.13372326]
 [15.58291559 19.86110046 15.13912063  7.84246644 11.01766689 11.15056361
  19.9829581 ]]
[[0.49805921 0.81446899 0.09282746 0.22061329 0.46916645 0.03115635
  0.91439725]
 [0.90082964 0.16475389 0.38660674 0.2406219  0.53812451 0.64729695
  0.56128002]
 [0.85361361 0.91087796 0.         0.40447794 0.14302897 0.41042698
  0.80635613]
 [0.77864659 0.99386969 0.75632055 0.389247   0.54898214 0.55566779
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
m = np.random.randint(0,11, size=(8,10)) # генерируем рандом матрицу 10 на 8
print(m)
mini = 1000
ind = 0
a = [sum(i) for i in m] # сумма строки в матрице m
for j in range(len(a)):
  if a[j] < mini:
    mini = a[j]
    ind = j # индекс наименьшей строки в матрице
print('Строка:',m[ind])
print('Минимальная сумма:', mini, 'Индекс строки:', ind+1,)

[[ 2  5  2 10 10  2  3  4  7  0]
 [ 0  9  4  2  4  4 10  7  2  4]
 [ 0  5  6  1  0  6  2  8  4  6]
 [ 8  1  8  0  8  2  9  5  8  5]
 [10  2  9  8  1  4  3  0  9  6]
 [ 6  6  5 10  8  6  9  4  3  4]
 [ 0  4  1  2  6  0  0  6  0  7]
 [ 6  8  0  1  0  5  3  7  6  3]]
Строка: [0 4 1 2 6 0 0 6 0 7]
Минимальная сумма: 26 Индекс строки: 7


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([9,8,7])
res = np.linalg.norm(a - b) # евклидово расстояние
print(res)

10.770329614269007


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
minC = np.array([[7, 21], [11, 8], [8, 4]]) * (-1) # -С
# X = A^(-1) * (-C) * B^(-1)
A_1 = np.linalg.inv(A) # это библиотечная функция numpy, которая вычисляет обратную матрицу
B_1 = np.linalg.inv(B) # вычисляем обр. матрицу В
res = np.dot(A_1, minC) # производим матричное умножение обратнрй матрицы А и -С
res1 = np.dot(res, B_1) # перемножаем полученный результат с обратной матрицей В
print(res1)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
import numpy as np # импортируем библиотеки
import pandas as pd
data = pd.read_csv('minutes_n_ingredients.csv', skiprows = 1, header = None) # считываем файл
# skiprows позволяет пропустить заданное кол-во строк сверху. в данном случае мы пропускаем заголовки столбцов
a = np.array(data) # создаем массив с помощью np.array
print(a[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('2 столбец:')
print(np.mean(a[:,1])) # среднее значение 2го столбца
print(np.min(a[:,1])) # минимум 2го столбца
print(np.max(a[:,1])) # максимум 2го столбца
print(np.median(a[:,1])) # медиана 2го столбца
print('\n3 столбец:') # с помощью \n3 делаем отступ
print(np.mean(a[:,2])) # тоже самое для 3го столбца
print(np.min(a[:,2]))
print(np.max(a[:,2]))
print(np.median(a[:,2]))

2 столбец:
21601.00169
0
2147483647
40.0

3 столбец:
9.05528
1
39
9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
print(np.quantile(a[:,1], .75)) #В статистике квантилем называется величина, которая делит набор данных на две равные части.

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(np.sum(a[:,1] == 0)) # смотрим, сколько рецептов с проолжительностью 0
(a[:,1])[a[:,1] == 0] = 1 # заменяем 0 на 1
print(np.sum(a[:,1] == 0)) # проверка

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(len(np.unique(a[:,0]))) # метод np.unique ищет уникальные значения

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
sett = set(a[:,2]) # создаем множество, которое исключает повторы
print(len(sett)) # выводим длину множества
print(sett) # выводим само множество

37
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37, 39}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
five = a[np.where(a[:,2] <= 5)] # создаем массив five, в который добавляем инфу о рецептах с заданным требованием
print(five)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
ave = a[: , 2] / a[: , 1] # создаем массив ave, в который добавл. среднее кол-во рецептов в минуту
print(max(ave)) # находим максимальное значение этой величины

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
sorted_data = a[a[:, 1].argsort()[::-1]] # сортируем данные по продолжительности от большей к меньшей
top = sorted_data[:100] # в top кладем первые 100 рецептов с данными о приготовлении
avg_ingredients = np.average(top[:, 2]) # считаем среднее кол-во ингредиентов
print('Ср кол-во ингредиентов для топ-100 рецептов:', avg_ingredients)

Ср кол-во ингредиентов для топ-100 рецептов: 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
total = a.shape[0] # кол-во строк
random_ind = np.random.choice(total, size=10, replace = False) # выбираем рандомные рецепты
random_rec = a[random_ind] # создаем массив с информацией о рандобных рецептах
print(random_rec) # инфо о 10 случайных рецептах

[[149226     50     16]
 [ 24516     10      4]
 [288398     50     14]
 [ 76643     35      7]
 [285319     40      7]
 [117874     25      7]
 [445354     45     10]
 [264666     50      9]
 [250519     75      7]
 [323973    130      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
len(np.where(a[:,2] < a[:,2].mean())[0])/a.shape[0]*100 # mean позволяет найти среднее значение
# а[:,2] - ингредиенты
# домножаем на 100, чтобы получить процент таких рецептов

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
gr = np.zeros((a.shape[0], 4), dtype=int)
gr !!!!!!!!!!!

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

13. Выведите процент "простых" рецептов в датасете

In [ ]:
str(sum(gr[:, 3])/a.shape[0]*100) !!!!!!!

SyntaxError: invalid syntax (<ipython-input-19-121c81dc3468>, line 1)

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.